### ISSUE TITLE
Support and compatibility with Webpack 4 regarding mini-css-extract-plugin

### ISSUE THREAD

**Issue by thasmo** [bensampaio/external-svg-sprite-loader#93]
First off, thanks for taking ownership of the package, maintaining and upgrading it for webpack 5. Thank a lot!

We ran into problems with `external-svg-sprite-loader@6` and `mini-css-extract-plugin@1.3` when running it wih `webpack@4`. I've noticed there was a [fix for the latest major version](https://github.com/bensampaio/external-svg-sprite-loader/pull/89) `7.x`, but it seems this fix was not implemented in the `6.x` branch; which seems to me as if `6.x` is not maintained anymore.

```
/node_modules/external-svg-sprite-loader/lib/SvgSprite.js:191
source = source.replace(originalResourcePathRegExp, resourcePath);
                ^
TypeError: source.replace is not a function
```

I understand that maintaining two separate versions is a lot of work but I hope you are considering adding the fix to the `v6` version too, as `mini-css-extract-plugin@1.3` supports `webpack@4` as well afaik.

Thanks for your input on this issue!

**Comment by thasmo** [comment]
@bensampaio, is this something you'd consider?

**Comment by bensampaio** [comment]
@thasmo thanks for reporting this issue. I would like to help but since I maintain this plugin alone I can't offer support for all versions. Therefore, I chose to offer support only for the current major version. Is there no option for you to upgrade to webpack@5? If not and if you are interested I could also invite you as a collaborator so that you can make the necessary change in a separate release branch.

**Comment by thasmo** [comment]
@bensampaio I totally understand your point of view. We're in the process of evaluating and upgrading webpack to version 5, but due to various dependent factors we don't be able to upgrade to webpack 5 shortly. If it's okay for you, feel free to create a separate branch and assign the relevant permissions to me, so I'm able to make the neccessary changes. Publishing releases for that branch on npm would probably still be on your side, I guess. Thanks a lot!

**Comment by bensampaio** [comment]
@thasmo I invited you as a collaborator and created branch `6.0`. You can branch out from that branch and create a PR with the changes for me to review. I will then publish the release.

**Comment by thasmo** [comment]
@bensampaio, thanks! Going to have a look at it soon.

**Comment by thasmo** [comment]
@bensampaio I was able to test `6.0.2` on a project of ours and so far everything looks good. 👍 Thanks for the time, help and cooperation. 🙇‍♂️
